### ISSUE TITLE
Inferencing with provided models returns empty instances

### ISSUE THREAD

**Issue by k00shan** [zetyquickly/DensePoseFnL#19] opened 2023-02-20 12:47 UTC
`I` am using the provided models on images to make prediction, but it doesn't find anything even with min score of .001.
I tested apply_net show and it just returned a gray scale image of the input.

what is the problem?

python apply_net.py show ./configs/mobile_parsing_rcnn_b_cse_s3x.yaml ./configs/mobile_parsing_rcnn_b_cse_s3x.pth ./imgs/test.jpg dp_contour,bbox,dp_segm,dp_v,dp_u --output out.png

![out 0001](https://user-images.githubusercontent.com/109728604/220141846-a150edb3-8756-4a8f-8a94-2e3818e3e19b.png)

**Comment by zetyquickly** [comment] 2023-02-20 17:43
Hello,

Try not to mix dp_segm, dp_v, dp_u they are conflicting somehow

Refer to the doc https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/TOOL_APPLY_NET.md

**Comment by k00shan** [comment] 2023-02-21 13:20
Thanks for the reply, I just need the human segmentation and even using one of them doesnt return any segmentation. Just the gray scale image.

python apply_net.py show ./configs/mobile_parsing_rcnn_b_s3x.yaml ./configs/mobile_parsing_rcnn_b_s3x.pth ./imgs/input.jpg dp_segm --output out.png -v

**Comment by k00shan** [comment] 2023-02-21 13:24
In general, I am trying to make inference on an image using these codes, but the instance is always 0.

cfg = get_cfg()
add_densepose_config(cfg)
add_timmnets_config(cfg)
cfg.merge_from_file('./configs/mobile_parsing_rcnn_b_s3x.yaml')
cfg.MODEL.WEIGHTS = './configs/mobile_parsing_rcnn_b_s3x.pth'
cfg.freeze()

predictor = DefaultPredictor(cfg)
img = read_image('./imgs/input.jpg', format="BGR") 

outputs = predictor(img)["instances"]

outputs:
Instances(num_instances=0, image_height=480, image_width=640, fields=[pred_boxes: Boxes(tensor([], device='cuda:0', size=(0, 4))), scores: tensor([], device='cuda:0'), pred_classes: tensor([], device='cuda:0', dtype=torch.int64)])

I tried with differnt images and it is always like this.
Am I missing something?

**Comment by k00shan** [comment] 2023-02-28 12:42
Hi,
Can you please help me with this issue? I can't figure the problem out. I am using the code above or apply_net.py show with all the povided models you put, but my instances are always empty on every images.

**Comment by zetyquickly** [comment] 2023-02-28 18:56
There was a successful use of `apply_net.py`. (https://github.com/zetyquickly/DensePoseFnL/issues/5#issuecomment-944916502)

**Comment by zetyquickly** [comment] 2023-02-28 19:23
I've just followed an instruction to install the repo from the README. Downloaded weights, put it into `model` folder. Downloaded some image of a human on a horse, put it into the `imgs` folder and run the `apply_net.py` with following command:

```python apply_net.py show ./configs/mobile_parsing_rcnn_b_s3x.yaml ./models/mobile_parsing_rcnn_b_s3x.pth  ./imgs/1.jpeg bbox,dp_segm -v```


And the output result is the following:
![1](https://user-images.githubusercontent.com/25350960/221957420-3afea47d-9fdc-4220-a1a7-deaf2a372502.jpeg)

Considering that I cannot reproduce your issue, and everything still works with fresh install. I'm closing this issue as resolved

![outputres 0001](https://user-images.githubusercontent.com/25350960/221957428-1ceb1ed8-12f8-4815-8091-afdfff3673fd.png)

**Closed as completed by zetyquickly** 2023-02-28 19:23 UTC
